# Generated by Django 2.1.7 on 2019-02-12 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos_on_sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentEntity',
            fields=[
                ('content_entity_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GenreEntity',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VideoEntity',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_title', models.CharField(max_length=300)),
                ('video_url', models.CharField(max_length=500)),
                ('genre_foreign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos_on_sale.GenreEntity')),
            ],
        ),
        migrations.CreateModel(
            name='VideoPackEntity',
            fields=[
                ('video_pack_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_pack_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VideosInPack',
            fields=[
                ('videos_in_pack_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_entity_foreign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos_on_sale.VideoEntity')),
                ('video_pack_entity_foreign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos_on_sale.VideoPackEntity')),
            ],
        ),
        migrations.AddField(
            model_name='videopackentity',
            name='video_pack_content_foreign_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos_on_sale.VideosInPack'),
        ),
        migrations.AddField(
            model_name='contententity',
            name='video_foreign_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos_on_sale.VideoEntity'),
        ),
        migrations.AddField(
            model_name='contententity',
            name='video_pack_foreign_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos_on_sale.VideoPackEntity'),
        ),
    ]
